default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: education_development

test:
  <<: *default
  database: education_test

production:
  <<: *default
  database: education_production
